
theme = "molokai"

[editor]
line-number = "relative"
rulers = [120]
bufferline = "always"
cursorline = true
color-modes = true

[keys.normal]
esc = ["collapse_selection"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-t = [":new", ":insert-output git log --graph --pretty=oneline --abbrev-commit", "collapse_selection"]

C-o = [":new", ":insert-output lf -print-selection", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file",  ":buffer-close!", ":redraw"]

C-q = ":buffer-close!"
C-n = ":new"
tab = ":buffer-next"
S-tab = ":buffer-previous"

C-7 = "toggle_comments"
"C-/" = "toggle_comments"

X = "extend_line_above" # Shift+x to select the whole line above
D = [ "extend_to_line_end", "change_selection"] # Wipe and edit the current line from cursor position


[keys.normal.t]
m = ":insert-output snippets m"
c = ":insert-output snippets c"
z = ":insert-output snippets z"
l = ":insert-output snippets l"
e = ":insert-output snippets e"

[keys.insert]

C-h = "move_char_left"
C-j = "move_visual_line_down"
C-k = "move_visual_line_up"
C-l = "move_char_right"
# S-j = ["normal_mode", "extend_to_line_bounds", "yank", "open_below", "replace_with_yanked", "collapse_selection"]
# S-k = ["normal_mode", "extend_to_line_bounds", "yank", "open_above", "replace_with_yanked", "collapse_selection"]

[editor.soft-wrap]
enable = true
# wrap-at-text-width = true
wrap-indicator = "↩ "

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.statusline]
right = [ "position", "position-percentage", "total-line-numbers" ]
left = [ "mode", "spinner", "diagnostics" ]
center = [ "file-name", "separator", "version-control", "separator" ]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# black popup
[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.file-picker]
hidden = false
